#!/usr/bin/env bash
################################################################################
# TaleCaster - https://github.com/rootwyrm/talecaster
# Copyright (C) 2015-* Phillip R. Jaenke <talecaster@rootwrym.com> and its
# contributors, all rights reserved.
#
# Licensed under CC-BY-NC-4.0
# See /LICENSE for details
################################################################################
# etc/periodic/weekly/certificates

## Update certificates on a weekly basis, to reduce stale chain risks.
apk upgrade -q -l --no-cache ca-certificates ca-certificates-bundle > /dev/null
