#!/usr/bin/env bash
################################################################################
# TaleCaster - https://github.com/rootwyrm/talecaster
# Copyright (C) 2015-* Phillip R. Jaenke <talecaster@rootwrym.com> and its
# contributors, all rights reserved.
#
# Licensed under CC-BY-NC-4.0
# See /LICENSE for details
################################################################################
# etc/periodic/weekly/dotnet

if [ -f /usr/local/share/dotnet ]; then
	## dotnet runtime is installed, update weekly to catch any security
	## fixes if the container itself wasn't updated first.
	/opt/talecaster/bin/update_dotnet.sh
else
	exit 0
fi
