#!/bin/bash

# Using the pre-build to edit the Dockerfile so we can cut down our 
# layer count.
# ---
# ./Dockerfile
# ./README.md
# ./hooks/
# ./sv/
# etc.

build_variables()
{
	touch ./build/pre_build.run
	printf 'GIT_REV = %s\n' "$(git rev-parse HEAD)" >> ./build/pre_build.run
	printf 'GIT_REV_SHORT = %s\n' "$(git rev-parse --short HEAD)" >> ./build/pre_build.run
	printf 'GIT_BRANCH = %s\n' "$(git rev-parse --short HEAD)" >> ./build/pre_build.run
	printf 'DATE_HASH = %s\n' "$(date +%d%m%y-%H%MZ | sha256sum | awk '{print $1}')" >> ./build/pre_build.run
	# get releaseid from /application/id.release
	# get servicename from /application/id.service
}

plug_variable_dockerfile()
{
	sed -i -e 's/\$'$1'/'$2'/' Dockerfile
}

build_variables
for v in `cat ./build/pre_build.run`; do
	plug_variable_dockerfile $(echo $v | cut -d = -f 1) $(echo $v | cut -d = -f 2)
done
