#!/bin/sh
## headphones/run

export tcuser=$(grep "TaleCaster User" /etc/passwd | cut -d : -f 1)
export tcgroup=$(getent group $tcuser | cut -d : -f 1)

cat /etc/motd

echo "[APPLICATION] Starting CouchPotato as $tcuser:$tcgroup"
echo " "
## NOTE: Cannot use backtick to format nicely.
exec chpst -u $tcuser:$tcgroup /opt/couchpotato/CouchPotato.py --data_dir=/config --pid_file /var/run/couchpotato/couchpotato.pid --console_log
