# Created by: TaleCaster <talecaster@rootwyrm.com>
# $TaleCaster: master/ports/talecaster/sonarr/Makefile

MASTERDIR=		${.CURDIR}/../../net-p2p/sonarr

USERS=	talecaster
GROUPS=	talecaster

.include "${MASTERDIR}/Makefile"
