name: "CICD - Development"
on:
  push:
    branches:
      - devel/*
    paths:
      - ci/**
      - container/**
  workflow_dispatch:
    
jobs:
  ############################################################
  # Base Image Check
  ############################################################
  tc_docker:
    name: "Development Build - tc_docker"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ tc_docker ]
    env:
      CONTAINER: ${{ matrix.container }}
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v3
      - name: Run pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Set tag
        id: tag
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/*" ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "main" ] && VERSION="latest"
          [ "$VERSION" == "latest" ] && VERSION="latest"
          [ "$VERSION" == "devel" ] && VERSION="devel"
          echo "::set-output name=VERSION::$(echo $VERSION)"
      - name: Setup qemu environment
        uses: docker/setup-qemu-action@v2
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v2
      - name: Log into ghcr.io
        id: docker_login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.container }}
        id: docker_push
        uses: docker/build-push-action@v3
        with:
          context: container/${{ matrix.container }}
          platforms: linux/amd64, linux/aarch64
          tags: ghcr.io/rootwyrm/${{ matrix.container }}:${{ steps.tag.outputs.VERSION }}
          pull: true
          push: true