name: CICD - Dockerfile Linter
on:
  push:
    paths:
      - container/**
  pull_request:
    paths:
      - container/**
  workflow_dispatch:
  workflow_call:

jobs:
  ############################################################
  # Linter
  ############################################################
  dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      lint: ${{steps.list.outputs.lint}}
    steps:
    - name: "Checkout @ ${{ github.ref }}"
      uses: actions/checkout@v3
    - name: Assemble output array
      id: list 
      run: |
        list=$(find ./container/ -name Dockerfile)
        echo lint=${list} >> ${GITHUB_OUTPUT}
      
  linter:
    runs-on: ubuntu-latest
    needs: dockerfiles
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    - name: lint
      uses: luke142367/Docker-Lint-Action@master
      with:
        target: ${{needs.dockerfiles.outputs.lint}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
