name: CICD - Dockerfile Linter
on:
  push:
    paths:
      - container/**
  pull_request:
    paths:
      - container/**
  workflow_dispatch:
  workflow_call:

jobs:
  ############################################################
  # Linter
  ############################################################
  linter:
    strategy:
      matrix:
        lint: [ tc_bazarr/Dockerfile, tc_docker/Dockerfile, tc_frontend/Dockerfile, tc_lidarr/Dockerfile, tc_mylar/Dockerfile, tc_nzbget/Dockerfile, tc_prowlarr/Dockerfile, tc_qbittorrent/Dockerfile, tc_radarr/Dockerfile, tc_readarr/Dockerfile, tc_sonarr/Dockerfile ]
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    ## https://github.com/hadolint/hadolint because there doesn't look to be a better option still.
    - name: lint
      ## Use a bash shell
      shell: bash
      env: 
        TARGET: ${{ matrix.lint }}
      run: |
        echo "Linting $TARGET"
        docker run --rm -i ghcr.io/hadolint/hadolint < ./container/$TARGET
