################################################################################
# TaleCaster - https://github.com/rootwyrm/talecaster
# Copyright (C) 2015-* Phillip R. Jaenke <talecaster@rootwrym.com> and its
# contributors, all rights reserved.
#
# Licensed under CC-BY-NC-4.0
# See /LICENSE for details
################################################################################
on:
  pull_request:
    branches:
      - latest
      - release/*
    tags:
      - v1*
        
## Build only for amd64 at this time, haven't moved on to aarch64 testing.
jobs:
  tc_docker:
    name: Pull Request - tc_docker
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_docker
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_mono:
    name: Pull Request - tc_mono
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_mono
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_frontend:
    name: Pull Request - tc_frontend
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_frontend
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_jackett:
    name: Pull Request - tc_jackett
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_docker
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_lidarr:
    name: Pull Request - tc_lidarr
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_lidarr
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_nzbget:
    name: Pull Request - tc_nzbget
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_nzbget
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_qbittorrent:
    name: Pull Request - tc_qbittorrent
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_qbittorrent
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_radarr:
    name: Pull Request - tc_radarr
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_radarr
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_sonarr:
    name: Pull Request - tc_sonarr
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_sonarr
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge
  tc_transmission:
    name: Pull Request - tc_transmission
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_transmission
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${CONTAINER}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          context: container/${CONTAINER}
          pull: true
          push: false
          tags: rootwyrm/${CONTAINER}:merge

# colorscheme=inkpot
# vim:ts=2:sw=2:et
