################################################################################
# TaleCaster - https://github.com/rootwyrm/talecaster
# Copyright (C) 2015-* Phillip R. Jaenke <talecaster@rootwrym.com> and its
# contributors, all rights reserved.
#
# Licensed under CC-BY-NC-4.0
# See /LICENSE for details
################################################################################
name: CICD - Pull Request Validator
on:
  pull_request:
    branches:
      - latest
      - release/*
    tags:
      - v1*

## Restructure to build our cores separate...        
jobs:
  ############################################################
  # tc_docker, tc_mono
  ############################################################
  base:
    name: Pull Request - base images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ tc_docker, tc_mono ]
    env:
      CONTAINER: ${{ matrix.container }}
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup qemu environment
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${{ matrix.container }}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/aarch64
          context: container/${{ matrix.container }}
          pull: true
          push: false
          tags: rootwyrm/${{ matrix.container }}:merge
  ############################################################
  # tc_qbittorrent - takes 1hr+
  ############################################################
  tc_qbittorrent:
    name: Pull Request - tc_mono
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_qbittorrent
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup qemu environment
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build tc_qbittorrent
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/aarch64
          context: container/$CONTAINER
          pull: true
          push: false
          tags: rootwyrm/tc_qbittorrent:merge
  ############################################################
  # tc_docker chidlren
  ############################################################
  tc_docker_child:
    name: Pull Request - tc_docker children
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ tc_frontend, tc_nzbget, tc_transmission, tc_lidarr, tc_radarr ]
    env:
      CONTAINER: ${{ matrix.container }}
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup qemu environment
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${{ matrix.container }}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/aarch64
          context: container/${{ matrix.container }}
          pull: true
          push: false
          tags: rootwyrm/${{ matrix.container }}:merge
  ############################################################
  # tc_mono children
  ############################################################
  tc_mono_child:
    name: Pull request - tc_mono children
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ tc_jackett, tc_sonarr ]
    env:
      CONTAINER: ${{ matrix.container }}
    steps:
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup qemu environment
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx environment
        uses: docker/setup-buildx-action@v1
      - name: Build ${{ matrix.container }}
        id: docker_nopush
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/aarch64
          context: container/${{ matrix.container }}
          pull: true
          push: false
          tags: rootwyrm/${{ matrix.container }}:merge

# colorscheme=inkpot
# vim:ts=2:sw=2:et
