## tc_docker
name: CI - tc_dotnet - minimum testing
on:
  push:
    branches:
      - master
      - release/*
    tags:
      - v1*
    paths:
      - 'docker/tc_dotnet/**'
  pull_request:
    branches:
      - master
      - release/*
    tags:
      - v1*
    paths:
      - 'docker/tc_dotnet/**'
  repository_dispatch:
    types: [ tc_mono ]

## Build only for amd64
jobs:
  base:
    name: tc_dotnet - minimum test ${{ github.ref }}
    runs-on: ubuntu-20.04
    env:
      CONTAINER: tc_dotnet
    steps:
    - name: tc_mono - check out from ${{ github.ref }} 
      id: checkout
      uses: actions/checkout@v2
#    - name: Run pre-build hooks
#      id: hooks
#      run: |
#        $GITHUB_WORKSPACE/ci/hooks/pre_build
#    - name: Set up build environment
#      id: buildenv
#      run: |
#        docker run --rm --privileged docker/binfmt:$BINFMT
#        docker buildx create --name rootwyrm --use
    - name: tc_dotnet - build ${{ github.ref }}
      ## We will never push
      run: |
        VERSION=citest
        docker build --pull --tag rootwyrm/$CONTAINER:$VERSION \
        docker/$CONTAINER -f docker/$CONAINER/Dockerfile.mintest
#docker push rootwyrm/$CONTAINER:$VERSION

# vim:ts=2:sw=2:et
