## tc_docker
name: CICD - docker
on:
  push:
    branches:
      - master
      - release/*
    tags:
      - v1*
    paths:
      - 'ci/hooks/**'
      - 'container/tc_docker/**'
  pull_request:
    branches:
      - master
      - release/*
    tags:
      - v1*
    paths:
      - 'ci/hooks/**'
      - 'container/tc_docker/**'
  repository_dispatch:
    types: [ tc_docker ]

## Build only for amd64
jobs:
  base:
    name: Build tc_docker - ${{ github.ref }}
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_docker
    steps:
    - name: Check out from ${{ github.ref }} 
      id: checkout
      uses: actions/checkout@v2
    - name: Run pre-build hooks
      id: hooks
      run: |
        $GITHUB_WORKSPACE/ci/hooks/pre_build 
    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_TOKEN }}
    - name: Build tc_docker - ${{ github.ref }}
      id: docker
      uses: docker/build-push-action@v2
      with:
        add_git_labels: true
        tag_with_ref: true
        always_pull: true
        platforms: linux/amd64
        context: container/tc_docker
        push: true
        tags: rootwyrm/tc_docker

# vim:ts=2:sw=2:et:colorscheme=inkpot
