################################################################################
# TaleCaster - https://github.com/rootwyrm/talecaster
# Copyright (C) 2015-* Phillip R. Jaenke <talecaster@rootwrym.com> and its
# contributors, all rights reserved.
#
# Licensed under CC-BY-NC-4.0
# See /LICENSE for details
################################################################################

name: PR - tc_docker
on:
  pull_request:
    paths:
      - container/tc_docker/**
    repository_dispatch:
      types: [ pr_tc_docker ]
  workflow_dispatch:

jobs:
  tc_docker:
    name: PR Check - tc_docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [ tc_docker ]
    env:
      CONTAINER: ${{ matrix.container }}
    steps:
      - name: Show job_id
        id: jobid
        uses: Tiryoh/gha-jobid-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: @@JOB_NAME@@
      - name: Check out from ${{ github.ref }}
        id: checkout
        uses: actions/checkout@v2
      - name: Test pre-build hooks
        id: hooks
        run: |
          $GITHUB_WORKSPACE/ci/hooks/pre_build
      - name: Setup qemu environment
        id: qemu-environment
        uses: docker/setup-qemu-action@v1
      - name: Setup buildx environment
        id: buildx-environment
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: env.BUILDKIT_STEP_LOG_MAX_SIZE=104857600
      - name: Test building ${{ matrix.container }}
        id: docker_buildx
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64, linux/arm64
          context: container/${{ matrix.container }}
          pull: true
          push: false
          tags: talecaster/${{ matrix.container }}:prcheck

# colorscheme=inkpot
# vim:ts=2:sw=2:et
