## tc_mono
name: CICD - tc_mono
on:
  push:
    branches:
      - master
      - release/*
    tags:
      - v1*
    paths:
      - 'ci/hooks/**'
      - 'container/tc_mono/**'
  pull_request:
    branches:
      - master
      - release/*
    tags:
      - v1*
    paths:
      - 'ci/hooks/**'
      - 'container/tc_mono/**'
  repository_dispatch:
    types: [ tc_mono ]

## Build only for amd64
jobs:
  base:
    name: Build tc_mono - ${{ github.ref }}
    runs-on: ubuntu-latest
    env:
      CONTAINER: tc_mono
    steps:
    - name: Check out from ${{ github.ref }} 
      id: checkout
      uses: actions/checkout@v2
    - name: Run pre-build hooks
      id: hooks
      run: |
        $GITHUB_WORKSPACE/ci/hooks/pre_build 
    - uses: docker/setup-buildx-action@v1
    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.HUB_USER }}
        password: ${{ secrets.HUB_TOKEN }}
    - name: Build tc_mono - ${{ github.ref }}
      id: docker
      uses: docker/build-push-action@v2
      with:
        platforms: linux/amd64
        context: container/tc_mono
        pull: true
        push: true
        tags: rootwyrm/tc_mono:latest
    ## Rebuild dependents.
    - name: Rebuild dependency tc_sonarr
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TRIGGER_TOKEN }}
        repository: ${{ github.repository }}
        event-type: tc_sonarr
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Rebuild dependency tc_radarr
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TRIGGER_TOKEN }}
        repository: ${{ github.repository }}
        event-type: tc_radarr
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Rebuild dependency tc_lidarr
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TRIGGER_TOKEN }}
        repository: ${{ github.repository }}
        event-type: tc_lidarr
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Rebuild dependency tc_jackett
      if: success()
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.TRIGGER_TOKEN }}
        repository: ${{ github.repository }}
        event-type: tc_jackett
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'


# colorscheme=inkpot
# vim:ts=2:sw=2:et
